### ISSUE TITLE
unable to enable plugin

### ISSUE THREAD

**Issue by hijak** [sethvargo/vault-secrets-gen#13]
Hi

I see this in the logs after registering the plugin and trying to run  
`vault secrets enable -path=gen vault-secrets-gen`

```
2019-10-26T00:18:26.068Z [ERROR] secrets.system.system_4c57e1d0: mount failed: path=gen/ error="Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol."
```

**Comment by hijak** [comment]
```
$ vault -version
Vault v1.2.3
```

**Comment by sethvargo** [comment]
What version of the plugin?

**Comment by hijak** [comment]
latest release from here

**Comment by sethvargo** [comment]
Hi @hijak 

I just verified that the latest release (v0.0.4) works with Vault v1.2.3 without issues. Are you sure you downloaded the correct binary for the target system? Make sure you picked the right architecture and operating system, as each binary is different.
