### ISSUE TITLE
Target Vault Version is not Documented

### ISSUE THREAD

**Issue by cheyngoodman** [sethvargo/vault-secrets-gen#17]
I believe the documentation should include a target version for Vault compatibility.

It appears `v.0.0.5` is the current release for this plugin. I have issues with the current Vault release `v1.3.1`. I believe there is some incompatibility in versions but can't find documentation on what version of Vault this plugin targets.

The plugin will register but doesn't function and cannot be removed.

Specifically I get `500` errors that may be due to incompatible plugin versions.
```
Error writing data to gen/password: Error making API request.

URL: PUT http://localhost:8200/v1/gen/password
Code: 500. Errors:

* 1 error occurred:
	* internal error
```

When attempting to remove the plugin.
```
Error disabling secrets engine at gen/: Error making API request.

URL: DELETE http://localhost:8200/v1/sys/mounts/gen
Code: 400. Errors:

* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

If this plugin is tested before it's released, what versions are known to work?

Can you include a section in the `README.md` with expected working versions?

**Comment by sethvargo** [comment]
The target Vault version is "whatever was released at the time when I compiled it". Each time there's a new release of Vault, we have to re-compile the plugin.

I just released 0.0.6.

**Comment by cheyngoodman** [comment]
The plug-in release is tied to a specific version of Vault, that you know and don't share when releasing...

Thanks for the quick release! I'll try compiling myself when troubleshooting next time.

**Comment by sethvargo** [comment]
It's in the release notes on GitHub: https://github.com/sethvargo/vault-secrets-gen/releases/tag/v0.0.6
