### ISSUE TITLE
Unable to enable the secrets engine

### ISSUE THREAD

**Issue by KalyanGvr** [sethvargo/vault-secrets-gen#24]
Hi,
I have a linux x86_64 architecture instance running the vault service in 1.2.2 version. I have downloaded the file vault-secrets-gen_0.0.5_linux_amd64.zip unzipped on a jump host, transferred the vault-secret-gen file to the linux under /opt/vault/plugins directory (have mentioned this path for plugins in vault config file).
Successfully registered the plugin, however while enabling the secrets engine got below error.

vault secrets enable -path="gen" -plugin-name="secrets-gen" plugin
Error enabling: Error making API request.
URL: POST https://<vaulthostedurl>:8200/v1/sys/mounts/gen
Code: 400. Errors:
* fork/exec /opt/vault/plugins/vault-secrets-gen: exec format error

Could you advice where am I going wrong ?

Regards,
Kalyan

**Comment by sethvargo** [comment]
That error means youre using the wrong binary. Is your target system linux x86_64?

**Comment by sethvargo** [comment]
Also, the latest version is v0.1.1

**Comment by KalyanGvr** [comment]
Yes, my target system is Linux x86_64, hence I am using Linuxamd64 plugin file. I hope this is the file for linux x86_64, please suggest if any other plugin file should be used. 
Not sure if the plugin 0.1.1 would support vault version 1.2.2, as you had mentioned plugin 0.0.6 supports vault 1.3, hence used 0.0.5

**Comment by jmls** [comment]
I'm using vault 1.5.3 , using alpine linux and the `vault-secrets-gen_0.1.1_linux_amd64` download

when trying to load the plugin, I get 

```
vault secrets enable -path="password" -plugin-name="secrets-gen" plugin
2020-09-24T18:22:10.983Z [ERROR] secrets.system.system_26235019: error occurred during enable mount: path=password/ error="fork/exec /vault/plugins/vault-secrets-gen: operation not permitted"
Error enabling: Error making API request.

URL: POST http://localhost:8201/v1/sys/mounts/password
Code: 400. Errors:

* fork/exec /vault/plugins/vault-secrets-gen: operation not permitted

```

what am I doing wrong ?

**Comment by voiprodrigo** [comment]
@jmls that's a different issue than the OP. But it definitely seems like a filesystem permissions problem. Probably the vault-secrets-gen isn't executable by the user that runs the Vault process, or that user can't traverse the path.

**Comment by voiprodrigo** [comment]
@KalyanGvr it surely seems you downloaded the wrong the file for the wrong architecture, or the file you downloaded wasn't cross-compiled for the architecture that the filename suggests.
One way to check directly is to try to execute the plugin directly in the filesystem, like so:
/opt/vault/plugins/vault-secrets-gen -h
This should list the plugin arguments.
