### ISSUE TITLE
Error writing data to gen/password: Error making API request.

### ISSUE THREAD

**Issue by TheDemonCat** [sethvargo/vault-secrets-gen#25]
After registering the plugin, I get an error:

consul and vault deployed in docker containers. Сonsul run launched with parameter network_mode: "host".
I execute the command under the admin token

```
/ # vault write gen/password length=36 symbols=0
Error writing data to gen/password: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/gen/password
Code: 500. Errors:

* 1 error occurred:
        * internal error
```

```
Vault v1.5.3 (9fcd81405feb320390b9d71e15a691c3bc1daeef)
Consul v1.8.3
```

```
{
    "storage":
    {
      "consul":
      {
        "address": "192.168.88.3:8500",
        "advertise_addr": "http://192.168.88.3:8500",
        "path": "vault/",
        "token": "<TOKEN>"
      }
    },
    "listener":
    {
      "tcp":
      {
        "address": "0.0.0.0:8200",
        "tls_disable_client_certs": true,
        "tls_disable" : "true"
      }
    },
    "log_level": "DEBUG",
    "ui": true,
    "plugin_directory": "/vault/data/plugins"
  }
  
```
LOGS

```


vault          | 2020-09-04T04:58:50.226Z [DEBUG] secrets.secrets-gen.secrets-gen_387f3b2d.secrets-gen: starting plugin: path=/vault/data/plugins/vault-secrets-gen args=[/vault/data/plugins/vault-secrets-gen]
vault          | 2020-09-04T04:58:50.226Z [DEBUG] secrets.secrets-gen.secrets-gen_387f3b2d.secrets-gen: plugin started: path=/vault/data/plugins/vault-secrets-gen pid=332
vault          | 2020-09-04T04:58:50.226Z [DEBUG] secrets.secrets-gen.secrets-gen_387f3b2d.secrets-gen: waiting for RPC address: path=/vault/data/plugins/vault-secrets-gen
vault          | 2020-09-04T04:58:50.297Z [ERROR] secrets.secrets-gen.secrets-gen_387f3b2d.secrets-gen.vault-secrets-gen: plugin tls init: error="error during token unwrap request: no value found at "cubbyhole/response"" timestamp=2020-09-04T04:58:50.296Z
vault          | 2020-09-04T04:58:50.332Z [ERROR] core: failed to run existence check: error="Unrecognized remote plugin message: 
vault          | 
vault          | This usually means that the plugin is either invalid or simply
vault          | needs to be recompiled to support the latest protocol."
vault          | 2020-09-04T04:58:50.332Z [DEBUG] secrets.secrets-gen.secrets-gen_387f3b2d.secrets-gen: plugin process exited: path=/vault/data/plugins/vault-secrets-gen pid=332

```

**Comment by sethvargo** [comment]
Yup - that happens on each Vault upgrade and I have to compile and release new versions 😦

**Comment by sethvargo** [comment]
Use v0.1.1

**Comment by TheDemonCat** [comment]
Version 2 did not help me( The error is the same
```
/vault/data/plugins # vault write gen/password length=36 symbols=0
Error writing data to gen/password: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/gen/password
Code: 500. Errors:

* 1 error occurred:
        * internal error
```

Vault v1.5.3 (9fcd81405feb320390b9d71e15a691c3bc1daeef)

**Comment by sethvargo** [comment]
I just tried with Vault 1.5.3 - are you sure the error is the same in the Vault server logs?

**Comment by TheDemonCat** [comment]
vault logs
```
nwrap request: no value found at "cubbyhole/response"" timestamp=2020-09-10T05:08:23.438Z
vault          | 2020-09-10T05:08:23.457Z [ERROR] rollback: error rolling back: path=gen/ error="Unrecognized remote plugin message: 
vault          | 2020-09-10T05:09:23.499Z [ERROR] secrets.secrets-gen.secrets-gen_545b3e1f.secrets-gen.vault-secrets-gen: plugin tls init: error="error during token unwrap request: no value found at "cubbyhole/response"" timestamp=2020-09-10T05:09:23.499Z
vault          | 2020-09-10T05:09:23.537Z [ERROR] rollback: error rolling back: path=gen/ error="Unrecognized remote plugin message: 
vault          | 2020-09-10T05:10:23.489Z [ERROR] secrets.secrets-gen.secrets-gen_545b3e1f.secrets-gen.vault-secrets-gen: plugin tls init: error="error during token unwrap request: no value found at "cubbyhole/response"" timestamp=2020-09-10T05:10:23.489Z
vault          | 2020-09-10T05:10:23.527Z [ERROR] rollback: error rolling back: path=gen/ error="Unrecognized remote plugin message: 
vault          | 2020-09-10T05:11:23.494Z [ERROR] secrets.secrets-gen.secrets-gen_545b3e1f.secrets-gen.vault-secrets-gen: plugin tls init: error="error during token unwrap request: no value found at "cubbyhole/response"" timestamp=2020-09-10T05:11:23.494Z
```

**Comment by sethvargo** [comment]
Sorry, but I'm not really sure how to help. That version is working for me on both Linux and Mac:

```text
             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Go Version: go1.14.7
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: debug
                   Mlock: supported: false, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.5.3
             Version Sha: 9fcd81405feb320390b9d71e15a691c3bc1daeef
```

```text
vault write -f gen/password
Key      Value
---      -----
value    K6U\.:t#A|cLlrfFwWVynv!JCUh2FWxPggTc%1BcDV9lqgx&2f|A6vH]7o3N8dE7
```

Can you run `./scripts/dev.sh` in this repo and see what happens?

**Comment by sethvargo** [comment]
Bump

**Comment by TheDemonCat** [comment]
I can only watch it on Monday. Very busy now(

**Comment by jossansone** [comment]
I think I'm having a similar issue.  The odd thing is this was working just last week when I set it up. Vault 1.5.3 and plugin version 0.1.1:
2020-09-22T16:36:32.205-0400 [DEBUG] secrets.secrets-gen.secrets-gen_c6e06724.secrets-gen: starting plugin: path=/etc/vault.d/plugins/vault-secrets-gen args=[/etc/vault.d/plugins/vault-secrets-gen]
2020-09-22T16:36:32.207-0400 [DEBUG] secrets.secrets-gen.secrets-gen_c6e06724.secrets-gen: plugin started: path=/etc/vault.d/plugins/vault-secrets-gen pid=6534
2020-09-22T16:36:32.209-0400 [DEBUG] secrets.secrets-gen.secrets-gen_c6e06724.secrets-gen: waiting for RPC address: path=/etc/vault.d/plugins/vault-secrets-gen
2020-09-22T16:36:36.494-0400 [ERROR] secrets.secrets-gen.secrets-gen_c6e06724.secrets-gen.vault-secrets-gen: plugin tls init: error="error during token unwrap request: Put "https://<vault address removed>/dev1/sys/wrapping/unwrap": Temporary Redirect" timestamp=2020-09-22T16:36:36.493-0400
2020-09-22T16:36:36.495-0400 [ERROR] rollback: error rolling back: path=gen/ error="Unrecognized remote plugin message:
This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol."
2020-09-22T16:36:36.495-0400 [DEBUG] secrets.secrets-gen.secrets-gen_c6e06724.secrets-gen: plugin process exited: path=/etc/vault.d/plugins/vault-secrets-gen pid=6534

I've tried reinstalling and re-enabling the plugin - all seems to work OK until I try to use it. even running vault read gen/info results in the same error:
![image](https://user-images.githubusercontent.com/71731930/93935392-890f7c00-fcf2-11ea-8ddd-ada08ee7a832.png)

**Comment by jossansone** [comment]
Nevermind, I just figured it out.  My issue was apparently being caused by Proxy address in systemv init script. Removing that resolved the issue.

**Comment by bxaxa** [comment]
Same error

/ # vault write gen/password length=36 symbols=0
Error writing data to gen/password: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/gen/password
Code: 500. Errors:

* 1 error occurred:
        * internal error

I'm using vault 1.4.0 or 1.5.3 Enterprise version, with local storage and 3 nodes.
