### ISSUE TITLE
Unrecognized remote plugin message

### ISSUE THREAD

**Issue by mr-menno** [sethvargo/vault-secrets-gen#27]
Tried both v0.1.1 and v1.5.4 combination, as well as v0.1.0 and v1.4.7 and various permutations.  

Getting this error, and can't find a guidance on troubleshooting this.  Hopefully this can serve as a reference for others.

vault    | 2020-10-21T22:52:45.696Z [ERROR] secrets.system.system_6ac02fcb: error occurred during enable mount: path=secrets-gen/ error="Unrecognized remote plugin message: 
vault    | 
vault    | This usually means that the plugin is either invalid or simply
vault    | needs to be recompiled to support the latest protocol."

**Comment by sethvargo** [comment]
What version of Vault?

**Comment by mr-menno** [comment]
Tried both 1.4.7 and 1.5.4

**Comment by sethvargo** [comment]
Each time there's a new version of Vault, I have to build and re-compile this plugin. Can you try building it yourself (make dev)?

**Comment by mr-menno** [comment]
I’ll have to try that.

Which version is v0.1.1 release compatible with?
