### ISSUE TITLE
"plugin exited before we could connect" while mount

### ISSUE THREAD

**Issue by mlowicki** [sethvargo/vault-secrets-gen#3]
```
> vault mount -path="gen" -plugin-name="secrets-gen" plugin
...
* plugin exited before we could connect
```

Vault  0.9.1

I've tried:
* https://github.com/sethvargo/vault-secrets-gen/releases/download/v0.0.1/vault-secrets-gen_0.0.1_linux_amd64.tgz
* https://github.com/sethvargo/vault-secrets-gen/releases/download/v0.0.1/vault-secrets-gen_0.0.1_linux_amd64.zip

on `Linux 70f3206690e2 4.6.0-0.bpo.1-amd64 #1 SMP Debian 4.6.1-1~bpo8+1 (2016-06-14) x86_64 Linux`.

In logs I see only:
```
2018/03/07 11:25:23.956931 [ERROR] sys: mount failed: path=gen/ error=plugin exited before we could connect
```

top-level `api_address` is set (as suggested in https://github.com/sethvargo/vault-secrets-gen/issues/2).

**Comment by mlowicki** [comment]
top-level `api_address` is set (as suggested in https://github.com/sethvargo/vault-secrets-gen/issues/2).

**Comment by sethvargo** [comment]
Hey @mlowicki 

I'm unable to reproduce this on my end, but I don't have access to that version of Debian. Can you please try using Vault 0.9.4 (or later) and the latest version of the plugin (v0.0.2)?

**Comment by illenseer** [comment]
I think, we had the same problem. If Vault is using `mlock`, then the plugin needs the capability, too:
`setcap cap_ipc_lock=+ep <path_to_plugin>/vault-secrets-gen`

**Comment by sethvargo** [comment]
Closing due to lack of response.
