### ISSUE TITLE
same error like "Unrecognized remote plugin message #27"

### ISSUE THREAD

**Issue by emper0r** [sethvargo/vault-secrets-gen#37]
### TL;DR

Hi @sethvargo 
I saw in the issue #27 you need to recompile every time vault out a new version... i'm using right now 1.9.2 server container and 1.9.2 of vault client... using with your last version stable of vault-secrets-gen and i can reach to register plugin but not to enable it.
can you verify if a new compiled version using 1.9.2 can fix it.... thanks

### Vault CLI (or API) output

```text
vault plugin register \
>     -sha256="${SHA256}" \
>     -command="vault-secrets-gen" \
>     secret secrets-gen
Success! Registered plugin: secrets-gen

vault secrets enable \
>     -path="gen" \
>     -plugin-name="secrets-gen" \
>     plugin
Error enabling: Error making API request.

URL: POST https://vault.server.domain/v1/sys/mounts/gen
Code: 400. Errors:

* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

### Vault server logs
```
2022-01-12T18:42:41.718Z [ERROR] secrets.system.system_8f71414c: error occurred during enable mount: path=gen/
error=
| Unrecognized remote plugin message:
|
| This usually means that the plugin is either invalid or simply
| needs to be recompiled to support the latest protocol.
```

### Additional information

server: vault:1.9.2 (docker)
client: Vault v1.9.2 (f4c6d873e2767c0d6853b5d9ffc77b0d297bfbdf)
vault-secrets-gen: 1.0.6

**Comment by sethvargo** [comment]
Those are the Vault _audit_ logs. What do the vault _server_ logs show?

**Comment by emper0r** [comment]
2022-01-12T18:42:41.718Z [ERROR] secrets.system.system_8f71414c: error occurred during enable mount: path=gen/
  error=
  | Unrecognized remote plugin message:
  |
  | This usually means that the plugin is either invalid or simply
  | needs to be recompiled to support the latest protocol.

**Comment by emper0r** [comment]
Ok.. tell how..
