### ISSUE TITLE
Worked for a couple of months… died suddenly.

### ISSUE THREAD

**Issue by dmilith** [sethvargo/vault-secrets-gen#41]
### TL;DR

`vault write -field=value gen/password length=50 symbols=0` used to work normally for a couple of months. Today it started to respond with:

```
…
Code: 404. Errors:

* no handler for route "gen/password". route entry found, but backend is nil.
```

### Expected behavior

Generated password, as before.

### Observed behavior

No vault upgrades or restarts were made for months.

### Vault CLI (or API) output

```text
Code: 404. Errors:

* no handler for route "gen/password". route entry found, but backend is nil.
```

### Vault server logs

```text
No logs
```

**Comment by dmilith** [comment]
@sethvargo Yeah… I also have no idea, it suddenly just stopped working this morning, while I'm certain no upgrades were made to the `vault` since I'd have to unseal the Vault manually. We use it on daily basis in my ${DAYJOB}. We've been using this plugin heavily for months :)


> `* no handler for route "gen/password". route entry found, but the backend is nil.`

This line from the error suggests that maybe I should upgrade `vault` on my production. But generally, everything else seems to work normally.

**Comment by sethvargo** [comment]
Are you sure Vault isn't panicing? Look at the Vault _server_ logs.

**Comment by dmilith** [comment]
Yeah, I'm pretty sure, nothing weird in the logs. The vault itself works as intended. Just the backend is nil for the plugin.

I will upgrade the vault later this month, so we'll see if the upgrade will help.

**Comment by dmilith** [comment]
@sethvargo I think I've found the reason for that issue. Vault all of a sudden decided to switch leader with a follower node which lacks that plugin (installed it only on the leader).

Which explains it's not the plugin's fault :)

Thanks for your help!
