### ISSUE TITLE
500 internal error when requesting passphrase/password

### ISSUE THREAD

**Issue by virtualhobbit** [sethvargo/vault-secrets-gen#7]
Unable to generate passphrases or passwords using Vault 1.0.2 and vault-secrets-gen 0.2.

Receive 500 internal error:

Error writing to: gen/passphrase.
URL: /v1/gen/passphrase
Code: 500
Errors:
  1 error occurred:
	* internal error

Plugin is registered fine.

**Comment by sethvargo** [comment]
This is because of https://github.com/hashicorp/go-plugin/issues/94. Use 1.0.1 for now. There's nothing I can do on this end unfortunately. Sorry!

**Comment by virtualhobbit** [comment]
Unfortunately I get the same error on Vault 1.0.0 and 1.0.1 :-(
